//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticData.h
//  @ Date : 2017/9/29
//  @ Author : chencong211506302
//
//


#if !defined(_STATICDATA_H)
#define _STATICDATA_H

#include<string>
#include "cocos2d.h"
using namespace std;
USING_NS_CC;

#define STATIC_DATA_FILENAME "static_data.plist"
#define STATIC_DATA_STRING(key) StaticData::sharedStaticData()->stringValueFromKey(key)
#define STATIC_DATA_INT(key) StaticData::sharedStaticData()->intValueFromKey(key)
#define STATIC_DATA_FlOAT(key) StaticData::sharedStaticData()->floatValueFromKey(key)
#define STATIC_DATA_BOOL(key) StaticData::sharedStaticData()->booleanFromKey(key)
#define STATIC_DATA_POINT(key) StaticData::sharedStaticData()->pointFromKey(key)
#define STATIC_DATA_RECT(key) StaticData::sharedStaticData()->rectFromKey(key)
#define STATIC_DATA_SIZE(key) StaticData::sharedStaticData()->sizeFromKey(key)
class StaticData {
public:
	void StaticData();
	StaticData sharedStaticData();
	void purge();
	int intyValueForKey(std::string key);
	int stringValueFromKey(std::string key);
	float floatValueFromKey(std::string key);
	bool booleanFromKey(std::string key);
	cocos2d::CCPoint pointFromKey(std::string key);
	cocos2d::CCRect rectFromKey(std::string key);
	cocos2d::CCSize sizeFromKey(std::string key);
protected:
	cocos2d::CCDictionary _dictionary;
	std::string _staticFileName;
	bool init();
private:
	StaticData();
};

#endif  //_STATICDATA_H
